-- Seed REAL menus_v2 des de CSV (Menú treballadors 2026)
-- Generat automàticament
-- Opcional: netejar abans d'importar
DELETE FROM public.menus_v2;

INSERT INTO public.menus_v2 (dish_name, diet_type, meal_type, day, course) VALUES
('AMANIDA DE PASTA amb ou i tonyina apart', 'omnivora', 'dinar', 'dilluns', 'primer'),
('ARRÒS AMB VERDURES AL WOK', 'omnivora', 'dinar', 'dimarts', 'primer'),
('PASTA BOLONYESA / PESTO', 'omnivora', 'dinar', 'dimecres', 'primer'),
('AMANIDA DE CIGRONS amb ou i tonyina apart', 'omnivora', 'dinar', 'dijous', 'primer'),
('PAELLA O FIDEUÀ', 'omnivora', 'dinar', 'divendres', 'primer'),
('AMANIDA RUSSA amb ou i tonyina apart', 'omnivora', 'dinar', 'dissabte', 'primer'),
('ARRÒS A LA CUBANA amb ous estrellats', 'omnivora', 'dinar', 'diumenge', 'primer'),
('AMANIDA DE PASTA', 'vegana', 'dinar', 'dilluns', 'primer'),
('ARRÒS AMB VERDURES AL WOK', 'vegana', 'dinar', 'dimarts', 'primer'),
('PASTA NAPOLITANA', 'vegana', 'dinar', 'dimecres', 'primer'),
('AMANIDA DE CIGRONS', 'vegana', 'dinar', 'dijous', 'primer'),
('PAELLA DE VERDURES', 'vegana', 'dinar', 'divendres', 'primer'),
('AMANIDA RUSSA', 'vegana', 'dinar', 'dissabte', 'primer'),
('ARRÒS A LA CUBANA', 'vegana', 'dinar', 'diumenge', 'primer'),
('SALSITXES amb patates fregides', 'omnivora', 'dinar', 'dilluns', 'segon'),
('LLOM AMB SALSA DE FORMATGE', 'omnivora', 'dinar', 'dimarts', 'segon'),
('POLLASTRE EMPANAT amb patates fregides', 'omnivora', 'dinar', 'dimecres', 'segon'),
('PEBROT FARCIT DE CARN', 'omnivora', 'dinar', 'dijous', 'segon'),
('FILET DE VEDELLA amb patates fregides', 'omnivora', 'dinar', 'dissabte', 'segon'),
('PIT DE POLLASTRE', 'omnivora', 'dinar', 'diumenge', 'segon'),
('HAMBURGUESA DE CARXOFA', 'vegana', 'dinar', 'dilluns', 'segon'),
('SALTAT DE XAMPINYONS I PÈSOLS', 'vegana', 'dinar', 'dimarts', 'segon'),
('FAJITAS VEGANES', 'vegana', 'dinar', 'dimecres', 'segon'),
('PEBROT FARCIT DE VERDURES', 'vegana', 'dinar', 'dijous', 'segon'),
('SAMFAINA AMB LLEGUMS', 'vegana', 'dinar', 'dissabte', 'segon'),
('KATSU D''AUBERGINIA', 'vegana', 'dinar', 'diumenge', 'segon'),
('PIZZA O / V / Ve', 'omnivora', 'sopar', 'dilluns', 'primer'),
('AMANIDA DE PATATA', 'omnivora', 'sopar', 'dimarts', 'primer'),
('AMANIDA VERDA', 'omnivora', 'sopar', 'dimecres', 'primer'),
('VERDURES PLANXA / SALTEJADES', 'omnivora', 'sopar', 'dijous', 'primer'),
('PÈSOLS SALTATS AMB PERNIL', 'omnivora', 'sopar', 'divendres', 'primer'),
('AMANIDA TOMÀQUET amb Mozzarella', 'omnivora', 'sopar', 'dissabte', 'primer'),
('SALMOREJO', 'omnivora', 'sopar', 'diumenge', 'primer'),
('AMANIDA DE PATATA', 'vegana', 'sopar', 'dimarts', 'primer'),
('AMANIDA VERDA', 'vegana', 'sopar', 'dimecres', 'primer'),
('VERDURES PLANXA / SALTEJADES', 'vegana', 'sopar', 'dijous', 'primer'),
('PÈSOLS SALTATS AMB VERDURES', 'vegana', 'sopar', 'divendres', 'primer'),
('AMANIDA TOMÀQUET', 'vegana', 'sopar', 'dissabte', 'primer'),
('SALMOREJO', 'vegana', 'sopar', 'diumenge', 'primer'),
('VARIAT DE CROQUETES I ALETES', 'omnivora', 'sopar', 'dimarts', 'segon'),
('PEIX A LA PLANXA amb patata panadera', 'omnivora', 'sopar', 'dimecres', 'segon'),
('CANELONS DE CARN', 'omnivora', 'sopar', 'dijous', 'segon'),
('HAMBURGUESA VEDELLA amb patates fregides', 'omnivora', 'sopar', 'divendres', 'segon'),
('POLLASTRE AL FORN amb patates', 'omnivora', 'sopar', 'dissabte', 'segon'),
('MANDONGUILLES EN SALSA', 'omnivora', 'sopar', 'diumenge', 'segon'),
('TOFU SALTAT A LA SOJA amb ceba i pebrot', 'vegana', 'sopar', 'dimarts', 'segon'),
('SOJA TEXTURIZADA amb arròs', 'vegana', 'sopar', 'dimecres', 'segon'),
('TOFU FREGIT', 'vegana', 'sopar', 'dijous', 'segon'),
('HAMBURGUESA HEURA amb patates fregides', 'vegana', 'sopar', 'divendres', 'segon'),
('HUMMUS', 'vegana', 'sopar', 'dissabte', 'segon'),
('CHANAMASANA', 'vegana', 'sopar', 'diumenge', 'segon');
